---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCmziUHq3jH7Z6FG6a6d/JFyBY5PrhuyOK3BJUDlFtm/UOOWPQepHjWR4+qlyBYiBYtduZ66WiV7qLg9MKSImt9ae25ENU0aKJvcdw+KO6xh2g8c8vb7zKykSLbQPXgCW/2zR/RTzss2JP2nPfYb3EwscVIY1hPCRz3be+FXgp2e1PVMNdxZk7WbjM000WspcxzT5KNAqjWEGHLQdjkFiqSZ7lTsirD+R7elwkdsPS9NUuG4iCbuPjObrkhIg00hMgLx5EdFoeNlMF7ebzqPcWD0m72qpfLsKlhetkvSnl8EHI2mHtGX5D6kJkzdXLi1qPyw+71dZG3cpmys36qQqY9pOK2/HeAIT/lr4Pu+UoEjGEhdYgwzHfKrJltEYDVHeJ1zU6vsHmIi75Z28nA3KVUD85ScL5swG7MtlwmxUuL5OHtJvRbo1O4Gz2CxmXYaiMVV85HqlHomFLv0urkdIKf9HgQ66AEJRVqnWP0tXn1yzx+y+Tbq+X7Mo1rAPjS/xOOU5/dMHZMyRwBzbHB+EatcQoZ02tcd3l4PeWJ+mz60AUUu3s3knZhrRq/UnGMcaHdVCad2e4IP33Sw0ij96zHoDzvJ6buoPT2s4C3CScpNwm1L0nxFsAhllSwoDFoljZHX63s1kUix7KlqoO5zQPBnNVY+XyBfS/8E0Z8lR0et6ZRDr/g3uo3ZCvhAA826lEs+AXcwT4BoYd31YGbk9AlAkMByR7MZ5lWrcd209wCcuucB0QE9cCkmn5jGctPIZewZQrHIryF1ogpIRZciN2WT03i/MD7zwS9iWlwwcIPw+ZuczPoRv/ZhStYgHiUvcTUYauSJo99W/YXdMEL23vYvAVyOyM8KInvzsmvI1mC47K4wyVyHPSBzHU5b3emLpmtyfb7RhXSd/QQ9Bw7MS8M3goJDcw1GPxMLqQdbnCjc23bLR3ZN/7wa+rqycWRC2Ov2+pxYETY3pViBd/W7yNCFoQIgIsrw/Ze6l9zoM/B3jP5zgndRlYqrZeGOx2XhVI=
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare
    type: Opaque
