apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/avramukk/homelab.git
    targetRevision: main
    path: infra/status/gatus/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
