---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    admin-password: AgClp+1uDfop0dQsDmsjexYcMjOzb45hOSG3ZH026CcvX9uX8uG1L6LRq9GCtNOI3oCfnsg2Go36G3xoHQ+t5sO4Wdlz5jEzi7ez2+hEJPErFwGswMdoiRKwZpJgGTp5S2+cTorRqiS9D6FlButtXMw3JDzD7I/zwirBq88ZomzCNt9tuJARXoSq/wnT0bUdyePQbFh31so4ng+1u5n6xairtXEMVCRVsStBib/2MWHwsQAwrR3U2y+wTN/yrxjr7R06n1hqpKJkDPj3AyeGAdXRvKNlmRj8Dt5/tUg2DzKpRv34YLDtz/+PWvi5Actu7wsag8LuPVp8b9aCslmQK1UNM8ND5TpWW3sXTy+lkfvcaYnD6phGfNslMwSifBEg9eZ5z0eViLuLSt6OR5JCxkfx7VoNOikjbpK1DCbXRBPId14EHJnpe6cwO+qJ+xCDn+MJRHdmkw6dQT84GpIDnr9J64dBLGRl4VOY7ezN9YLcSje5/UHYC/J/pNI8Bw0s76Fk+4squSIE4pKNtz+u5XmnVkzJXKh7r3ICrTI2dzswDWhiFWXBku/oAdNTaL9NxsWU6TNOthMnIIQ5xKb5KK27m8WgoLyd0jYJzPE31o9o1dwZfT1/XJmohWQ77mF2BM7mnIwlqjSlkiWj0/BmBCJJ3ZixxbuPWtwJRjqd42ZmUHfcjJogW+QJ2ZVTbJuYuQ7hIwS4DtZdyfYAKujubNfTZasrSoeyc9OGFvxd
    admin-user: AgAmdPJwaxkTIw/tfse6YJ1DgjL0do+eqC9wKKa0D5ugbt5NtAY81aLVDVejBFjqCHlgbtzSlFbGRsLhUF6i1EZu5agJYNEBl9HPkCLJ8baJptjtuNrvrt5nqh8Hq/lHjnonmbzza4QwxEdubSGnnAvJsCfG0l1yIgpBsKkWDH1pJpiMTg5E3crZrOtlLtns/lxW6CcXFvew2KVEnzgb+YaxyYP6rMnO4jTsKxV3CCqXxdLbphcJyTlS4X5J2FY/nUsscx/JyPbLEhoT8grosLL4UjjZhKWhonsWHr+0xrRiDZE2veC92+B4kXaIfrJRD2NdVFCdZRgROj+trKvb8PQ3k3iLliksJsCdJfFg30cMg8y8+tnr4irRMQ5zL4KU5zk5dhmGXyEkjzcqHYA3PkJMSHB/9FVa/eukGIDgRdx8xCDG59oSuGkS040mW7OT6pMIIgHN8vg37/JRbS7ekE6BwDNE4Ms6cdctGseYEVKL/uuVl7qgIVCo3o6Km1pMucAnz+372Rb8TCJ1cVrXHo8GQmJOopM3jy/Nrm6WaWoYIYdiWtrb/yHOIGg4UiZaCk519jD8Csy/3VVCNRtT+snmO60p8zHcg91/WAws+V6u/X0TsSIrY/HcUb75qJ1D1U4ezVMGCEW4IP5tm7BeVe4F0VfV8gJY5XBeVrmrDGvNxZ6Pl+7/Ck2D/t5yw+jPcUbM4CtuzA==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
