---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAmqT07304AV2PH2gJjqZ7VWr2aCFxXT2S7kwgCczxTt8j3rGjsaZcAKEQVzHcsXw2qM0/UZycuGmvsZuxiKYDx/fsnEZcEIUbmeq0lo0hJ9mqiMYw+DNopr7ho+7o5ZDJfhZqzwM/jYysOE1XfoqHsrtUp5rOMbpCNfQW5FWdKWkglTY30ZGg52HmI0mGf8FnjHRf7r1eqyD2ZeiOp+mbet6N0OPGUHp1lRxw2fMC9d0mzs1fyZmja/TRdROqV8Aw5b+13HySzRn6AKWEMjCUsqL1Mo9BgorpJUkGquYydDgoo6m27/XebqhqT3mGKcRIbFaO5M59a8xMzfvVrxCRSmAwXWzgZ8oRVpYsXeHv9Dcj55XNjs0ihOHVvdoikQieBQdihd/OWeGuObsgbdWw3nvkpKxRwEoPODUAARDR1Oku3LjiuHoRwJjZDzW/fRhmZcTS0SVDgyIkfsxsjhS9xoYVfnzTKUH3moqyWx3QQdnxkUYuqXZ678caXou7zUtJCpif1cKtq8cXQG+tdnAgcmRmpznm+8Lrf4saXrOQ11MFrXNUA7x31JhPyA7MqBuiQ4IllGR5itgGFv+c2lXhW7NYNxA2DPmURR5m0zq+aNhXJxhQqrZkiMwTt47r982LoSxApAzmdRopC8ovxC+OnC3cd0hfALVemruELqUNIfCgEiUARmOrYxWC2uSqkyy3L9SOgpdMU4Xs1wV7LKXeIt48X8jZeCQA0SrDtu8waWQL7Hd/GE908ZxUQiXjv1o0neMhVkQ==
  template:
    metadata:
      name: cloudflare-dns
      namespace: traefik
    type: Opaque
